export const CROP_SAVE_REQUEST = "CROP_SAVE_REQUEST";
export const CROP_SAVE_SUCCESS = "CROP_SAVE_SUCCESS";
export const CROP_SAVE_FAIL = "CROP_SAVE_FAIL";

export const CROP_LIST_REQUEST = "CROP_LIST_REQUEST";
export const CROP_LIST_SUCCESS = "CROP_LIST_SUCCESS";
export const CROP_LIST_FAIL = "CROP_LIST_FAIL";

export const CROP_LIST_ONE_REQUEST = "CROP_LIST_ONE_REQUEST";
export const CROP_LIST_ONE_SUCCESS = "CROP_LIST_ONE_SUCCESS";
export const CROP_LIST_ONE_FAIL = "CROP_LIST_ONE_FAIL";

export const CROP_DELETE_ONE_REQUEST = "CROP_DELETE_ONE_REQUEST";
export const CROP_DELETE_ONE_SUCCESS = "CROP_DELETE_ONE_SUCCESS";
export const CROP_DELETE_ONE_FAIL = "CROP_DELETE_ONE_FAIL";
