export const REQ_SAVE_REQUEST = "REQ_SAVE_REQUEST";
export const REQ_SAVE_SUCCESS = "REQ_SAVE_SUCCESS";
export const REQ_SAVE_FAIL = "REQ_SAVE_FAIL";

export const REQ_LIST_REQUEST = "REQ_LIST_REQUEST";
export const REQ_LIST_SUCCESS = "REQ_LIST_SUCCESS";
export const REQ_LIST_FAIL = "REQ_LIST_FAIL";

export const REQ_LIST_ONE_REQUEST = "REQ_LIST_ONE_REQUEST";
export const REQ_LIST_ONE_SUCCESS = "REQ_LIST_ONE_SUCCESS";
export const REQ_LIST_ONE_FAIL = "REQ_LIST_ONE_FAIL";

export const REQ_UPDATE_ONE_REQUEST = "REQ_UPDATE_ONE_REQUEST";
export const REQ_UPDATE_ONE_SUCCESS = "REQ_UPDATE_ONE_SUCCESS";
export const REQ_UPDATE_ONE_FAIL = "REQ_UPDATE_ONE_FAIL";
